services:
  mysql:
    image: mysql:8.4
    container_name: ai-commerce-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} #解除耦合避免密码泄露
      MYSQL_DATABASE: ai_commerce
    ports:
      - "3307:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-time-zone=+08:00
    volumes:
      - mysql-data:/var/lib/mysql


  redis:
    image: redis:7.4
    container_name: ai-commerce-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes #让 Redis 开启追加日志持久化，重启后数据更不容易丢
    volumes:
      - redis-data:/data
  
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: ai-commerce-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  mysql-data:
  redis-data:
  rabbitmq-data: