<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import MerchantShell from '../../components/MerchantShell.vue'
import StatusPill from '../../components/StatusPill.vue'
import { getMerchantProducts, type MerchantProductItem } from '../../api/product'
import { currency } from '../../data/consumerCatalog'
const products=ref<MerchantProductItem[]>([]); const demo=ref(false)
const onSale=computed(()=>products.value.filter(p=>p.status==='ON_SALE').length)
const stock=computed(()=>products.value.reduce((sum,p)=>sum+p.totalAvailableStock,0))
async function load(){try{products.value=await getMerchantProducts({page:1,size:5})}catch{demo.value=true;products.value=[{id:1,name:'澄澈降噪耳机',description:'轻盈贴耳',status:'ON_SALE',skuCount:2,minSalePrice:699,totalAvailableStock:32,updatedAt:''},{id:2,name:'晨雾保温杯',description:'日常器物',status:'DRAFT',skuCount:2,minSalePrice:99,totalAvailableStock:80,updatedAt:''}]}}
onMounted(load)
</script>
<template><MerchantShell title="经营概览" eyebrow="TODAY / OVERVIEW"><template #actions><RouterLink class="button button--signal" to="/merchant/products/new">＋ 新增商品</RouterLink></template>
  <p v-if="demo" class="demo-banner">演示视图：服务不可用，趋势与待办为静态设计内容。</p>
  <section class="metric-grid"><article><span>商品总数</span><strong>{{products.length}}</strong><small>当前目录</small></article><article><span>上架商品</span><strong>{{onSale}}</strong><small>消费者可见</small></article><article><span>可售库存</span><strong>{{stock}}</strong><small>全部 SKU 合计</small></article><article class="dark"><span>今日待办</span><strong>03</strong><small>静态预览</small></article></section>
  <section class="dashboard-grid"><article class="panel"><div class="panel-head"><div><p class="meta-label">CATALOG PULSE</p><h2>最近商品</h2></div><RouterLink to="/merchant/products">查看全部 →</RouterLink></div><div v-for="p in products.slice(0,4)" :key="p.id" class="product-row"><span>{{p.name.slice(0,1)}}</span><div><b>{{p.name}}</b><small>{{p.skuCount}} SKU · {{currency(p.minSalePrice)}}</small></div><StatusPill :status="p.status"/></div></article><article class="panel tasks"><div class="panel-head"><div><p class="meta-label">NEXT ACTION</p><h2>经营待办</h2></div><em>静态</em></div><label><input type="checkbox">补充低库存商品</label><label><input type="checkbox">完善新品视觉素材</label><label><input type="checkbox">回看本周订单趋势</label></article></section>
</MerchantShell></template>
<style scoped>.demo-banner{padding:12px 15px;margin:0 0 22px;background:#eef6d4;color:#485b12;font-size:12px}.metric-grid{display:grid;grid-template-columns:repeat(4,1fr);border:1px solid var(--merchant-line)}.metric-grid article{min-height:165px;padding:24px;border-right:1px solid var(--merchant-line);display:grid;align-content:space-between}.metric-grid article:last-child{border:0}.metric-grid span,.metric-grid small{font-size:12px;color:var(--merchant-muted)}.metric-grid strong{font:500 45px/1 var(--font-display)}.metric-grid .dark{background:var(--merchant-ink);color:#fff}.dashboard-grid{display:grid;grid-template-columns:1.4fr .7fr;gap:22px;margin-top:22px}.panel{border:1px solid var(--merchant-line);padding:26px}.panel-head{display:flex;justify-content:space-between;align-items:start;margin-bottom:30px}.panel-head h2{margin:9px 0 0;font-size:22px}.panel-head a,.panel-head em{font-size:12px;color:var(--merchant-muted);font-style:normal}.product-row{display:grid;grid-template-columns:42px 1fr auto;align-items:center;gap:14px;padding:14px 0;border-top:1px solid var(--merchant-line)}.product-row>span{display:grid;place-items:center;width:42px;height:42px;background:var(--merchant-soft)}.product-row b{display:block;font-size:14px}.product-row small{font-size:12px;color:var(--merchant-muted)}.tasks{display:flex;flex-direction:column}.tasks label{padding:19px 0;border-top:1px solid var(--merchant-line);font-size:13px}.tasks input{margin-right:10px}@media(max-width:900px){.metric-grid{grid-template-columns:1fr 1fr}.metric-grid article:nth-child(2){border-right:0}.metric-grid article{border-bottom:1px solid var(--merchant-line)}.dashboard-grid{grid-template-columns:1fr}}@media(max-width:560px){.metric-grid{grid-template-columns:1fr}.metric-grid article{border-right:0}}
</style>
