<script setup lang="ts">
import { computed, ref } from 'vue'
import { useRouter } from 'vue-router'
import MerchantShell from '../../components/MerchantShell.vue'
import { createMerchantProduct, createMerchantSku, publishMerchantProduct } from '../../api/product'
import { apiErrorMessage } from '../../api/http'

interface SkuDraft { skuName:string; salePrice:number; availableStock:number }
const router=useRouter(); const name=ref(''); const description=ref(''); const publishNow=ref(true)
const skus=ref<SkuDraft[]>([{skuName:'标准款',salePrice:99,availableStock:10}]); const saving=ref(false); const error=ref('')
const valid=computed(()=>name.value.trim().length>0&&skus.value.every(s=>s.skuName.trim()&&s.salePrice>=0&&s.availableStock>=0))
function addSku(){skus.value.push({skuName:`款式 ${skus.value.length+1}`,salePrice:99,availableStock:10})}
function removeSku(index:number){if(skus.value.length>1)skus.value.splice(index,1)}
async function submit(){if(!valid.value||saving.value)return;saving.value=true;error.value='';try{const product=await createMerchantProduct({name:name.value.trim(),description:description.value.trim()||undefined});for(const sku of skus.value)await createMerchantSku(product.id,sku);if(publishNow.value)await publishMerchantProduct(product.id);await router.push({path:'/merchant/products',query:{created:'1'}})}catch(caught){error.value=apiErrorMessage(caught)}finally{saving.value=false}}
</script>
<template><MerchantShell title="新增商品" eyebrow="CATALOG / CREATE"><template #actions><RouterLink class="button button--ghost" to="/merchant/products">取消</RouterLink></template>
  <form class="create-layout" @submit.prevent="submit"><div class="form-main"><section><div class="section-index">01</div><div><p class="meta-label">BASIC INFORMATION</p><h2>商品是什么？</h2><label>商品名称<input v-model.trim="name" maxlength="80" placeholder="例：晨雾保温杯"></label><label>商品描述<textarea v-model.trim="description" maxlength="500" placeholder="说清它适合谁、解决什么需要。"></textarea></label></div></section><section><div class="section-index">02</div><div><p class="meta-label">SELLING UNITS</p><h2>有哪些可售款式？</h2><article v-for="(sku,index) in skus" :key="index" class="sku-card"><header><b>SKU {{String(index+1).padStart(2,'0')}}</b><button type="button" @click="removeSku(index)">移除</button></header><div><label>款式名称<input v-model.trim="sku.skuName"></label><label>售价（元）<input v-model.number="sku.salePrice" type="number" min="0" step="0.01"></label><label>可售库存<input v-model.number="sku.availableStock" type="number" min="0" step="1"></label></div></article><button type="button" class="add-sku" @click="addSku">＋ 增加一个 SKU</button></div></section></div><aside><p class="meta-label">PUBLISHING</p><h2>发布检查</h2><ul><li :class="{done:name}">商品名称</li><li :class="{done:description}">清晰描述</li><li :class="{done:valid}">完整 SKU</li></ul><label class="publish-switch"><input v-model="publishNow" type="checkbox"><span>创建后立即上架</span></label><p>上架后消费者可以在公共商品页看到它。</p><p v-if="error" class="error">{{error}}</p><button class="button button--signal" type="submit" :disabled="!valid||saving">{{saving?'正在创建…':'创建商品'}}</button></aside></form>
</MerchantShell></template>
<style scoped>.create-layout{display:grid;grid-template-columns:minmax(0,1fr) 290px;gap:42px}.form-main section{display:grid;grid-template-columns:55px 1fr;gap:20px;padding:10px 0 55px;margin-bottom:42px;border-bottom:1px solid var(--merchant-line)}.section-index{font:500 24px var(--font-display)}.form-main h2,aside h2{margin:12px 0 32px;font-size:28px}.form-main label{display:grid;gap:9px;margin:20px 0;font-size:13px}.form-main input,.form-main textarea{width:100%;padding:14px;border:1px solid var(--merchant-line);background:#fff;font:inherit}.form-main textarea{min-height:120px;resize:vertical}.sku-card{padding:18px;margin:16px 0;background:var(--merchant-soft)}.sku-card header{display:flex;justify-content:space-between}.sku-card header b{font-size:12px}.sku-card header button,.add-sku{border:0;background:none;text-decoration:underline;font-size:12px}.sku-card>div{display:grid;grid-template-columns:1.4fr .8fr .8fr;gap:14px}.sku-card label{margin:14px 0 0}.add-sku{padding:12px 0}aside{position:sticky;top:30px;height:max-content;padding:24px;background:var(--merchant-ink);color:#fff}aside .meta-label,aside>p{color:#979c98}aside ul{list-style:none;padding:0;margin:0 0 25px}aside li{padding:13px 0;border-top:1px solid #343936;color:#858a86;font-size:13px}aside li:before{content:'○';margin-right:9px}aside li.done{color:#fff}aside li.done:before{content:'●';color:var(--signal)}.publish-switch{display:flex;gap:9px;padding:18px 0;border-top:1px solid #343936;font-size:13px}aside>p{font-size:12px;line-height:1.6}.error{color:#ff9d84!important}.button{width:100%;margin-top:15px}@media(max-width:900px){.create-layout{grid-template-columns:1fr}aside{position:static}}@media(max-width:620px){.form-main section{grid-template-columns:1fr}.sku-card>div{grid-template-columns:1fr}}
</style>
