<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import MerchantShell from '../../components/MerchantShell.vue'
import StatusPill from '../../components/StatusPill.vue'
import { getMerchantProducts, publishMerchantProduct, unpublishMerchantProduct, type MerchantProductItem } from '../../api/product'
import { apiErrorMessage } from '../../api/http'
import { currency } from '../../data/consumerCatalog'
const products=ref<MerchantProductItem[]>([]);const keyword=ref('');const filter=ref('ALL');const loading=ref(false);const error=ref('');const demo=ref(false);const changing=ref<number|null>(null)
const fallback:MerchantProductItem[]=[{id:1,name:'澄澈降噪耳机',description:'轻盈贴耳，把专注留给自己。',status:'ON_SALE',skuCount:2,minSalePrice:699,totalAvailableStock:32,updatedAt:'2026-08-09'},{id:2,name:'回声桌面音箱',description:'为一张桌子准备的声场。',status:'ON_SALE',skuCount:3,minSalePrice:289,totalAvailableStock:126,updatedAt:'2026-08-08'},{id:3,name:'晨雾保温杯',description:'从清晨到傍晚。',status:'DRAFT',skuCount:2,minSalePrice:99,totalAvailableStock:80,updatedAt:'2026-08-07'}]
const visible=computed(()=>products.value.filter(p=>(filter.value==='ALL'||p.status===filter.value)&&`${p.name}${p.description||''}`.toLowerCase().includes(keyword.value.toLowerCase())))
async function load(){loading.value=true;error.value='';demo.value=false;try{products.value=await getMerchantProducts({page:1,size:50,keyword:keyword.value||undefined});if(!products.value.length){products.value=fallback;demo.value=true}}catch(caught){products.value=fallback;demo.value=true;error.value='服务暂不可用，当前展示演示目录。'}finally{loading.value=false}}
async function toggle(product:MerchantProductItem){if(demo.value)return;changing.value=product.id;error.value='';try{if(product.status==='ON_SALE'){await unpublishMerchantProduct(product.id);product.status='OFF_SALE'}else{await publishMerchantProduct(product.id);product.status='ON_SALE'}}catch(caught){error.value=apiErrorMessage(caught)}finally{changing.value=null}}
onMounted(load)
</script>
<template><MerchantShell title="商品管理" eyebrow="CATALOG / PRODUCTS"><template #actions><RouterLink class="button button--signal" to="/merchant/products/new">＋ 新增商品</RouterLink></template>
  <section class="catalog-summary"><div><span>全部</span><strong>{{products.length}}</strong></div><div><span>上架中</span><strong>{{products.filter(p=>p.status==='ON_SALE').length}}</strong></div><div><span>总库存</span><strong>{{products.reduce((n,p)=>n+p.totalAvailableStock,0)}}</strong></div><p>一个清楚的目录，<br>让经营动作更轻。</p></section>
  <section class="toolbar"><div class="tabs"><button v-for="item in [{k:'ALL',l:'全部'},{k:'ON_SALE',l:'上架中'},{k:'DRAFT',l:'草稿'},{k:'OFF_SALE',l:'已下架'}]" :key="item.k" :class="{active:filter===item.k}" @click="filter=item.k">{{item.l}}</button></div><label><span>⌕</span><input v-model.trim="keyword" placeholder="搜索商品" @keyup.enter="load"></label></section>
  <p v-if="demo||error" class="demo-banner">{{error||'演示目录：创建与上下架仍会请求真实后端，当前演示条目不可操作。'}}</p>
  <section class="table-wrap"><div class="table-head"><span>商品</span><span>售价</span><span>库存</span><span>状态</span><span>动作</span></div><div v-if="loading" class="loading"><i v-for="i in 5" :key="i"/></div><article v-for="product in visible" v-else :key="product.id" class="product-row"><div class="product-name"><span>{{product.name.slice(0,1)}}</span><div><b>{{product.name}}</b><small>{{product.skuCount}} SKU · {{product.description}}</small></div></div><strong>{{currency(product.minSalePrice)}}</strong><span>{{product.totalAvailableStock}}</span><StatusPill :status="product.status"/><button type="button" :disabled="demo||changing===product.id" @click="toggle(product)">{{changing===product.id?'处理中…':product.status==='ON_SALE'?'下架':'上架'}}</button></article><div v-if="!loading&&!visible.length" class="empty"><h2>没有相符商品</h2><p>换一个筛选条件，或创建新的商品。</p></div></section>
</MerchantShell></template>
<style scoped>.catalog-summary{display:grid;grid-template-columns:repeat(3,150px) 1fr;align-items:end;padding:10px 0 28px}.catalog-summary div{display:grid;gap:7px}.catalog-summary span{font-size:12px;color:var(--merchant-muted)}.catalog-summary strong{font:500 30px var(--font-display)}.catalog-summary p{justify-self:end;margin:0;color:var(--merchant-muted);font-size:13px;line-height:1.5}.toolbar{display:flex;justify-content:space-between;align-items:center;border-block:1px solid var(--merchant-line)}.tabs{display:flex}.tabs button{padding:15px;border:0;background:none;color:var(--merchant-muted)}.tabs button.active{color:var(--merchant-ink);box-shadow:inset 0 -2px}.toolbar label{display:flex;align-items:center;gap:8px}.toolbar input{border:0;background:transparent;padding:12px;width:200px}.demo-banner{padding:11px 14px;margin:16px 0 0;background:#eef6d4;color:#485b12;font-size:12px}.table-head,.product-row{display:grid;grid-template-columns:minmax(280px,1.7fr) .65fr .5fr .65fr .55fr;gap:18px;align-items:center;border-bottom:1px solid var(--merchant-line)}.table-head{padding:15px 0;color:var(--merchant-muted);font-size:11px;text-transform:uppercase;letter-spacing:.08em}.product-row{min-height:86px;font-size:13px}.product-name{display:flex;align-items:center;gap:14px;min-width:0}.product-name>span{flex:0 0 42px;display:grid;place-items:center;height:42px;background:var(--merchant-soft)}.product-name b,.product-name small{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.product-name small{margin-top:5px;color:var(--merchant-muted);font-size:11px}.product-row>strong{font-weight:500}.product-row>button{justify-self:start;border:0;background:none;text-decoration:underline;font-size:12px}.product-row>button:disabled{opacity:.4}.loading i{display:block;height:86px;border-bottom:1px solid var(--merchant-line);background:linear-gradient(90deg,#fff,var(--merchant-soft),#fff);background-size:200%;animation:shimmer 1.2s infinite}.empty{padding:80px 0;text-align:center}.empty h2{font-size:23px}.empty p{color:var(--merchant-muted)}@keyframes shimmer{to{background-position:-200%}}@media(max-width:850px){.catalog-summary{grid-template-columns:repeat(3,1fr)}.catalog-summary p{display:none}.table-wrap{overflow:auto}.table-head,.product-row{min-width:720px}}@media(max-width:580px){.toolbar{align-items:stretch;flex-direction:column}.tabs{overflow:auto}.toolbar label{border-top:1px solid var(--merchant-line)}.catalog-summary strong{font-size:25px}}
</style>
