<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import ConsumerNav from '../../components/ConsumerNav.vue'
import { deleteCartItem, getCartItems, updateCartQuantity } from '../../api/cart'
type DisplayItem={id:number;skuId:number;quantity:number;name:string;skuName:string;price:number}
const loading=ref(true);const error=ref('');const items=ref<DisplayItem[]>([])
const demo=():DisplayItem[]=>[{id:1,skuId:1001,quantity:1,name:'无线降噪耳机',skuName:'曜石黑',price:699},{id:2,skuId:1003,quantity:2,name:'便携桌面音箱',skuName:'石墨灰',price:289}]
const total=computed(()=>items.value.reduce((sum,item)=>sum+item.price*item.quantity,0)); const count=computed(()=>items.value.reduce((sum,item)=>sum+item.quantity,0))
async function load(){loading.value=true;error.value='';try{const remote=await getCartItems();items.value=remote.map((i,index)=>({...demo()[index%2],...i}))}catch{const saved=localStorage.getItem('shelfflow_demo_cart');items.value=saved?JSON.parse(saved):demo();error.value='当前展示演示购物车数据'}finally{loading.value=false}}
async function change(item:DisplayItem,delta:number){const next=Math.max(1,item.quantity+delta);item.quantity=next;try{await updateCartQuantity(item.id,next)}catch{localStorage.setItem('shelfflow_demo_cart',JSON.stringify(items.value))}}
async function remove(item:DisplayItem){items.value=items.value.filter(x=>x.id!==item.id);try{await deleteCartItem(item.id)}catch{localStorage.setItem('shelfflow_demo_cart',JSON.stringify(items.value))}}
onMounted(load)
</script>
<template><div><ConsumerNav/><main class="cart-page"><header><p class="eyebrow">YOUR SELECTION</p><h1>购物车 <span v-if="!loading">{{ count }} 件</span></h1></header><p v-if="error" class="demo-note">{{ error }}</p><section v-if="loading" class="cart-layout"><div class="lines"><i v-for="i in 3" :key="i"/></div><div class="summary skeleton"/></section><section v-else-if="items.length" class="cart-layout"><div class="items"><article v-for="item in items" :key="item.id" class="cart-item"><img src="https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=400&q=75" :alt="item.name"/><div class="item-info"><h2>{{ item.name }}</h2><p>{{ item.skuName }}</p><button class="text-button remove" @click="remove(item)">移除</button></div><div class="item-price">¥ {{ item.price }}</div><div class="stepper"><button @click="change(item,-1)">−</button><span>{{ item.quantity }}</span><button @click="change(item,1)">＋</button></div></article></div><aside class="summary"><h2>订单摘要</h2><p><span>小计</span><span>¥ {{ total }}</span></p><p><span>运费</span><span>免运费</span></p><div><span>总计</span><strong>¥ {{ total }}</strong></div><button class="primary-button">提交订单</button><small>税费将在结算前确认。</small></aside></section><section v-else class="empty-state"><h2>你的购物车还是空的</h2><p>从店铺中选择一件喜欢的商品开始。</p><RouterLink class="primary-button empty-link" to="/stores/1/products">返回商品列表</RouterLink></section></main></div></template>
<style scoped>
.cart-page{max-width:1180px;margin:auto;padding:58px 32px}.eyebrow{font-size:12px;color:#5c5e62;letter-spacing:.7px;margin:0 0 14px}.cart-page h1{font-size:36px;font-weight:500;letter-spacing:-.6px;margin:0 0 46px}.cart-page h1 span{font-size:15px;color:#5c5e62;font-weight:400;margin-left:8px}.demo-note{font-size:12px;color:#8e8e8e;margin:-28px 0 24px}.cart-layout{display:grid;grid-template-columns:1fr 330px;gap:62px}.cart-item{display:grid;grid-template-columns:100px 1fr 90px 132px;gap:20px;align-items:center;padding:0 0 24px;margin-bottom:24px;border-bottom:1px solid #eee}.cart-item img{width:100px;height:100px;object-fit:cover;background:#f4f4f4}.cart-item h2,.summary h2{font-size:16px;font-weight:500;margin:0}.item-info p{font-size:13px;color:#5c5e62;margin:7px 0 17px}.remove{font-size:13px}.item-price{font-size:14px}.stepper{display:flex;align-items:center;justify-content:space-between;border:1px solid #eee;height:38px;border-radius:4px}.stepper button{width:37px;height:100%;border:0;background:#fff;font-size:17px}.stepper span{font-size:14px}.summary{height:max-content;padding:24px;background:rgba(245,245,247,.8);backdrop-filter:blur(20px) saturate(180%)}.summary h2{margin-bottom:24px}.summary p,.summary>div{display:flex;justify-content:space-between;font-size:14px;color:#5c5e62;margin:14px 0}.summary>div{padding-top:18px;border-top:1px solid rgba(23,26,32,.09);color:#171a20}.summary strong{font-size:19px;font-weight:500}.summary .primary-button{width:100%;margin-top:22px}.summary small{display:block;font-size:11px;color:#8e8e8e;text-align:center;margin-top:14px}.lines i{display:block;height:100px;margin-bottom:24px;background:#f4f4f4}.skeleton{height:250px;background:#f4f4f4}.empty-link{display:inline-grid;place-items:center;width:200px;margin:auto}@media(max-width:760px){.cart-page{padding:38px 16px}.cart-layout{grid-template-columns:1fr;gap:30px}.cart-item{grid-template-columns:76px 1fr 70px;gap:13px}.cart-item img{width:76px;height:76px}.stepper{grid-column:2/4;width:132px}.item-price{text-align:right}.summary{order:-1}}
</style>
