<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import ConsumerNav from '../../components/ConsumerNav.vue'
import { addCartItem } from '../../api/cart'
import { getProductDetail, type PublicProductDetail, type PublicSku } from '../../api/product'
const route=useRoute(); const router=useRouter(); const loading=ref(true); const product=ref<PublicProductDetail | null>(null); const selected=ref<PublicSku | null>(null); const quantity=ref(1); const message=ref('')
const demo:PublicProductDetail={id:Number(route.params.spuId),name:'无线降噪耳机',description:'为专注时刻而生。轻巧贴合，声音干净且有力量。',updatedAt:'',skus:[{id:1001,skuName:'曜石黑',salePrice:699,availableStock:32},{id:1002,skuName:'云雾白',salePrice:699,availableStock:18}]}
const current=computed(()=>selected.value || product.value?.skus[0] || demo.skus[0]); const canAdd=computed(()=>current.value.availableStock>0 && quantity.value>0 && quantity.value<=current.value.availableStock)
async function load(){loading.value=true;try{product.value=await getProductDetail(Number(route.params.spuId));selected.value=product.value.skus[0]}catch{product.value=demo;selected.value=demo.skus[0]}finally{loading.value=false}}
async function add(){if(!canAdd.value)return;message.value='';try{await addCartItem(current.value.id,quantity.value);message.value='已加入购物车'}catch{message.value='已加入演示购物车';localStorage.setItem('shelfflow_demo_cart',JSON.stringify([{id:Date.now(),skuId:current.value.id,quantity:quantity.value,name:product.value?.name||demo.name,skuName:current.value.skuName,price:current.value.salePrice}]))}setTimeout(()=>router.push('/cart'),500)}
onMounted(load)
</script>
<template><div><ConsumerNav/><main v-if="loading" class="detail-skeleton"><div/><div/></main><main v-else class="detail-page"><section class="detail-photo"><img src="https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1300&q=85" :alt="product?.name"/></section><section class="detail-info"><RouterLink class="back" to="/stores/1/products">返回商品列表</RouterLink><p class="eyebrow">SHELF / SELECTED</p><h1>{{ product?.name }}</h1><p class="description">{{ product?.description }}</p><p class="price">¥ {{ current.salePrice }}</p><div class="specs"><p>选择规格</p><div><button v-for="sku in product?.skus" :key="sku.id" class="sku" :class="{active:selected?.id===sku.id}" @click="selected=sku">{{ sku.skuName }}</button></div></div><p class="stock">{{ current.availableStock > 0 ? `库存 ${current.availableStock} 件` : '暂时售罄' }}</p><div class="quantity"><span>数量</span><button @click="quantity=Math.max(1,quantity-1)">−</button><span>{{ quantity }}</span><button @click="quantity=Math.min(current.availableStock,quantity+1)">＋</button></div><button class="primary-button add" :disabled="!canAdd" @click="add">{{ current.availableStock ? '加入购物车' : '暂时售罄' }}</button><p v-if="message" class="message">{{ message }}</p><p class="fine">下单前将再次确认库存与价格。</p></section></main></div></template>
<style scoped>
.detail-page{display:grid;grid-template-columns:1.15fr .85fr;min-height:calc(100dvh - 44px)}.detail-photo{background:#f4f4f4;min-height:680px}.detail-photo img{width:100%;height:100%;object-fit:cover}.detail-info{padding:64px clamp(32px,7vw,116px);align-self:center}.back{font-size:14px;color:#5c5e62}.eyebrow{font-size:12px;color:#5c5e62;letter-spacing:.7px;margin:70px 0 20px}.detail-info h1{font-size:42px;letter-spacing:-.8px;line-height:1.12;font-weight:500;margin:0}.description{font-size:17px;line-height:1.55;color:#393c41;max-width:420px;margin:20px 0 36px}.price{font-size:25px;font-weight:500;margin:0 0 42px}.specs>p,.stock{font-size:14px;color:#5c5e62;margin:0 0 12px}.sku{height:38px;background:#fff;border:1px solid #eee;border-radius:4px;padding:0 15px;margin-right:8px}.sku.active{border-color:#171a20;color:#171a20}.stock{margin-top:20px}.quantity{width:146px;border:1px solid #eee;border-radius:4px;height:40px;display:flex;align-items:center;justify-content:space-between;margin:28px 0}.quantity span:first-child{display:none}.quantity button{background:transparent;border:0;font-size:18px;width:42px;height:100%}.add{width:100%;max-width:340px}.message{font-size:14px;color:#393c41}.fine{font-size:12px;color:#8e8e8e}.detail-skeleton{display:grid;grid-template-columns:1.15fr .85fr;min-height:100dvh;gap:30px;padding:44px}.detail-skeleton>div{background:#f4f4f4}@media(max-width:760px){.detail-page{grid-template-columns:1fr}.detail-photo{min-height:380px}.detail-info{padding:32px 24px 50px}.eyebrow{margin-top:45px}.detail-info h1{font-size:33px}.detail-skeleton{grid-template-columns:1fr;padding:16px}.detail-skeleton>div{height:300px}}
</style>
