<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import ConsumerNav from '../../components/ConsumerNav.vue'
import { getStoreProducts, type PublicProductItem } from '../../api/product'
const products = ref<PublicProductItem[]>([]); const loading = ref(true); const error = ref(''); const keyword = ref('')
const demoProducts: PublicProductItem[] = [
  { id: 1, name: '无线降噪耳机', description: '沉浸听感，轻巧贴合', minSalePrice: 699, totalAvailableStock: 32, updatedAt: '' },
  { id: 2, name: '便携桌面音箱', description: '紧凑却饱满的桌面声场', minSalePrice: 289, totalAvailableStock: 126, updatedAt: '' },
  { id: 3, name: '轻量保温杯', description: '适合每天随身携带', minSalePrice: 99, totalAvailableStock: 80, updatedAt: '' },
  { id: 4, name: '智能氛围灯', description: '为夜晚留一束恰好的光', minSalePrice: 159, totalAvailableStock: 21, updatedAt: '' },
  { id: 5, name: '掌上充电宝', description: '轻薄设计，长效续航', minSalePrice: 199, totalAvailableStock: 46, updatedAt: '' },
]
const filtered = computed(() => products.value.filter(p => p.name.includes(keyword.value) || p.description?.includes(keyword.value)))
const images = ['photo-1505740420928-5e560c06d30e','photo-1542291026-7eec264c27ff','photo-1527864550417-7fd91fc51a46','photo-1491553895911-0055eca6402d','photo-1511707171634-5f897ff02aa']
function photo(id:number) { return `https://images.unsplash.com/${images[id % images.length]}?auto=format&fit=crop&w=1000&q=80` }
async function load(){loading.value=true;error.value='';try{products.value=await getStoreProducts(1);if(!products.value.length)products.value=demoProducts}catch{products.value=demoProducts;error.value='当前展示演示商品，连接服务后将自动显示真实商品。'}finally{loading.value=false}}
onMounted(load)
</script>
<template><div><ConsumerNav /><main class="store-page"><header class="store-intro"><div><p class="eyebrow">SHELF / 01</p><h1>为日常挑选<br>值得拥有的物件。</h1><p>成都示例商家 · 精选商品</p></div><img src="https://images.unsplash.com/photo-1449247709967-d4461a6a6103?auto=format&fit=crop&w=1200&q=85" alt="店铺陈列" /></header><section class="catalog-head"><div><h2>正在出售</h2><span>{{ products.length }} 件商品</span></div><input v-model="keyword" class="search-input" placeholder="搜索商品" /></section><p v-if="error" class="page-error catalog-message">{{ error }} <button class="text-button" @click="load">重新加载</button></p><section v-else-if="loading" class="product-grid skeleton-grid"><div v-for="i in 6" :key="i" class="skeleton" /></section><section v-else-if="filtered.length" class="product-grid"><RouterLink v-for="(item,index) in filtered" :key="item.id" :to="`/products/${item.id}`" class="product"><img :src="photo(index)" :alt="item.name" /><div><p class="product__name">{{ item.name }}</p><p class="product__desc">{{ item.description || '探索更多商品细节' }}</p><div class="product__bottom"><span>¥ {{ item.minSalePrice ?? '—' }}</span><span v-if="item.totalAvailableStock > 0">加入购物车</span><span v-else>暂时售罄</span></div></div></RouterLink></section><section v-else class="empty-state"><h2>没有找到相关商品</h2><button class="text-button" @click="keyword=''">清除搜索条件</button></section></main></div></template>
<style scoped>
.store-page{max-width:1384px;margin:auto;padding:34px 38px 84px}.store-intro{height:310px;display:grid;grid-template-columns:.9fr 1.1fr;background:#f4f4f4;overflow:hidden}.store-intro>div{padding:43px 46px}.eyebrow{font-size:12px;letter-spacing:.7px;margin:0 0 25px;color:#5c5e62}.store-intro h1{font-size:38px;line-height:1.14;font-weight:500;letter-spacing:-.7px;margin:0}.store-intro p:last-child{color:#5c5e62;font-size:14px;margin-top:26px}.store-intro img{width:100%;height:100%;object-fit:cover}.catalog-head{display:flex;justify-content:space-between;align-items:end;padding:50px 0 20px}.catalog-head div{display:flex;align-items:baseline;gap:12px}.catalog-head h2{font-size:24px;font-weight:500;margin:0}.catalog-head span{font-size:13px;color:#5c5e62}.catalog-head input{width:245px}.product-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:38px 20px}.product:nth-child(1){grid-column:span 2}.product img{display:block;width:100%;aspect-ratio:1/1;object-fit:cover;background:#f4f4f4;transition:opacity .33s}.product:hover img{opacity:.85}.product__name{font-size:16px;font-weight:500;margin:14px 0 5px}.product__desc{height:20px;color:#5c5e62;font-size:13px;margin:0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.product__bottom{display:flex;justify-content:space-between;margin-top:13px;font-size:14px}.product__bottom span:last-child{color:#5c5e62}.catalog-message{padding:36px 0}.skeleton{height:340px;background:#f4f4f4}.skeleton:nth-child(1){grid-column:span 2}.skeleton-grid{gap:20px}@media(max-width:760px){.store-page{padding:20px 16px 50px}.store-intro{height:auto;grid-template-columns:1fr}.store-intro>div{padding:32px 25px}.store-intro h1{font-size:31px}.store-intro img{height:190px}.catalog-head{align-items:start;gap:16px;flex-direction:column;padding-top:35px}.catalog-head input{width:100%}.product-grid{grid-template-columns:repeat(2,1fr);gap:28px 12px}.product:nth-child(1){grid-column:span 2}.product__desc{height:38px;white-space:normal}.product__bottom{display:block;line-height:1.8}.product__bottom span:last-child{display:block}.skeleton{height:220px}}
</style>
